### ISSUE TITLE
Nejde harvestovať LKOD MFSR

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#17]
https://opendata.mfsr.sk/opendata/catalog/lkod

Podľa logov sa obsah stiahol, ale súbor je len HTML stránka s obsahom: „OpenData portál MF SR je dočasne nedostupný . Za dočasné obmedzenie práce na portáli sa ospravedlňujeme.“
Teraz je ťažké povedať, či je to náhoda, alebo je to súčasť každodennej odstávky, ktorá prebieha v čase harvestovania.
 
PS: V čase písania tohto issue LKOD MFSR ide, uvidíme, či to bude pretrvávať.

**Comment by miroslavliska** [comment]
OK, vyzera to, ze MFSR dodali dobry katalog v JSON-LD, ale z nejakych dovodov LinkedPipes vyzaduje TTL:

> 2023-11-12 23:25:15,505 [Files to RDF single graph] ERROR c.l.p.t.f.FilesToRdfGraph - Can't parse file: https---opendata.mfsr.sk-opendata-catalog-lkod
> org.eclipse.rdf4j.rio.RDFParseException: Expected an RDF value here, found '{' [line 1]
> at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:347)
> at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:683)
> at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1309)
> at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:588)
> at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseSubject(TurtleParser.java:398)
> at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:333)
> at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:203)
> at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:165)
> at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:128)
> at com.linkedpipes.plugin.transformer.filesToRdfGraph.FilesToRdfGraph.loadEntry(FilesToRdfGraph.java:82)
> at com.linkedpipes.plugin.transformer.filesToRdfGraph.FilesToRdfGraph.loadFiles(FilesToRdfGraph.java:72)
> at com.linkedpipes.plugin.transformer.filesToRdfGraph.FilesToRdfGraph.execute(FilesToRdfGraph.java:47)
> at com.linkedpipes.etl.executor.api.v1.component.SequentialExecution.execute(SequentialExecution.java:11)
> at com.linkedpipes.etl.executor.plugin.v1.PluginV1Instance.execute(PluginV1Instance.java:37)
> at com.linkedpipes.etl.executor.component.SequentialComponentExecutor.run(SequentialComponentExecutor.java:39)
> at java.base/java.lang.Thread.run(Thread.java:833)

Takze toto musime zistit u dodavatelov NKODu.

**Comment by hornik-informo** [comment]
Testovanie harvestácie prosím presunúť do iného projektu. Webový portál a zdrojový kód v tomto repozitári harvestovanie nerieši.
